# Generated by Django 4.1.4 on 2023-01-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('Ans', models.CharField(max_length=3000)),
                ('title1', models.CharField(max_length=300)),
                ('Ans1', models.CharField(max_length=3000)),
                ('title2', models.CharField(max_length=300)),
                ('Ans2', models.CharField(max_length=3000)),
            ],
        ),
    ]
