# Generated by Django 4.1.4 on 2023-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0003_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('selected_op', models.CharField(max_length=100)),
            ],
        ),
    ]
