# Generated by Django 4.1.4 on 2023-01-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0004_pollsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollsdata',
            name='title',
        ),
    ]
