# Generated by Django 4.1.4 on 2023-01-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0005_remove_pollsdata_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pollsData',
        ),
    ]
