# Generated by Django 4.1.4 on 2023-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0006_delete_pollsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_op', models.CharField(max_length=400)),
            ],
        ),
    ]
